lib: [
  "_build/install/default/lib/ocaml_netaddr/META" {"META"}
  "_build/install/default/lib/ocaml_netaddr/opam" {"opam"}
  "_build/install/default/lib/ocaml_netaddr/netaddr.cmi"
  "_build/install/default/lib/ocaml_netaddr/netaddr.cmx"
  "_build/install/default/lib/ocaml_netaddr/netaddr.cmt"
  "_build/install/default/lib/ocaml_netaddr/netaddr.cmti"
  "_build/install/default/lib/ocaml_netaddr/netaddr.mli"
  "_build/install/default/lib/ocaml_netaddr/ocaml_netaddr.cma"
  "_build/install/default/lib/ocaml_netaddr/ocaml_netaddr.cmxa"
  "_build/install/default/lib/ocaml_netaddr/ocaml_netaddr.a"
  "_build/install/default/lib/ocaml_netaddr/ocaml_netaddr.cmxs"
]
